// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnELBPtORdbQSVf8VIFD17ngtyaLh7PNQ',
    appId: '1:1025066787133:web:e18274f26c590a3004e554',
    messagingSenderId: '1025066787133',
    projectId: 'gen-lang-client-0100404536',
    authDomain: 'gen-lang-client-0100404536.firebaseapp.com',
    storageBucket: 'gen-lang-client-0100404536.firebasestorage.app',
    measurementId: 'G-ZMV8WYK17D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfe7j1M6n9HBt8pNLvJYjLMIQ89OrriSo',
    appId: '1:1025066787133:android:6c769170743a989b04e554',
    messagingSenderId: '1025066787133',
    projectId: 'gen-lang-client-0100404536',
    storageBucket: 'gen-lang-client-0100404536.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGOLcQWVy-GMfrLYitCr9HxsBYEEuKgfM',
    appId: '1:1025066787133:ios:a8ac8e59a2d3aec904e554',
    messagingSenderId: '1025066787133',
    projectId: 'gen-lang-client-0100404536',
    storageBucket: 'gen-lang-client-0100404536.firebasestorage.app',
    iosClientId:
        '1025066787133-g7itk3mncretf8tdk82bstt7mqtio1lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.growvyClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGOLcQWVy-GMfrLYitCr9HxsBYEEuKgfM',
    appId: '1:1025066787133:ios:a8ac8e59a2d3aec904e554',
    messagingSenderId: '1025066787133',
    projectId: 'gen-lang-client-0100404536',
    storageBucket: 'gen-lang-client-0100404536.firebasestorage.app',
    iosClientId:
        '1025066787133-g7itk3mncretf8tdk82bstt7mqtio1lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.growvyClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnELBPtORdbQSVf8VIFD17ngtyaLh7PNQ',
    appId: '1:1025066787133:web:d85dd0200aa5341204e554',
    messagingSenderId: '1025066787133',
    projectId: 'gen-lang-client-0100404536',
    authDomain: 'gen-lang-client-0100404536.firebaseapp.com',
    storageBucket: 'gen-lang-client-0100404536.firebasestorage.app',
    measurementId: 'G-421XKGRM6K',
  );
}
